language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install: "pip install -r requirements/dev.txt"
script: py.test kakaravaara
before_install:
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - pip install codecov
after_success:
  - codecov
