language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install: "pip install -r requirements/dev.txt"
script: py.test kakaravaara
before_install:
  - pip install codecov
after_success:
  - codecov
