---
- name: Ensure locales are set
  lineinfile: line='LANGUAGE="en_US.UTF-8"' dest=/etc/default/locale state=present
- name: Ensure locales are set
  lineinfile: line='LC_ALL="en_US.UTF-8"' dest=/etc/default/locale state=present
- name: System dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - git
    - gettext
    # Postgresql
    - libpq-dev
    - postgresql-9.3
    - python-psycopg2
    # Apache
    - apache2
    # Pillow
    - python3-dev
    - python3-setuptools
    - libtiff5-dev
    - libjpeg8-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.6-dev
    - tk8.6-dev
    - python-tk
    # uWSGI
    - build-essential
    - python-dev
