---
- name: PostgreSQL system dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - libpq-dev
    - postgresql-9.3
    - python-psycopg2

- name: Create database
  postgresql_db: name={{ db_name }}
  become_user: postgres
- name: Create user
  postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL
  become_user: postgres
- name: Ensure user does not have unnecessary privilege
  postgresql_user: name={{ db_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become_user: postgres
