---
- name: Create database
  postgresql_db: name={{ db_name }}
  become_user: postgres
- name: Create user
  postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL
  become_user: postgres
- name: Ensure user does not have unnecessary privilege
  postgresql_user: name={{ db_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become_user: postgres
