---
- name: Ensure git.geneas.org is a known host
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa git.feneas.org') }}"
    regexp: "^git\\.feneas\\.org"
