---
- name: uWSGI log path
  file: path=/home/kakara/logs owner=kakara group=kakara state=directory
- name: uWSGI ini file
  template: src=kakara.ini dest=/home/kakara/kakara.ini

- name: Set up uWSGI systemd service
  template: dest=/etc/systemd/system/kakara.service src=systemd.conf
  notify:
    - restart kakara
